name: Java CI with Gradle

on: 
  push: 
    branches: ["master"]
  pull_request: 
    branches: ["master"]

  

jobs:
  test:
    name: Gradle_Java_Setup_And_Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
     
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: gradle version
        run: gradle -v
      - name: Grant Permissions to gradlew
        run: chmod +x gradlew
      - name: Gradle init
        run: gradle init
     
  build:
    name: 
    runs-on: ubuntu-latest
    steps:
    - name: Gradle init
      run: gradle init
    - name: Test
      run: gradle test --tests "*"
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

    